# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on: [push]
jobs:
    build_package:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                dapp:
                    - calculator
                    - converter
                    - echo-python
                    - echo-cpp
                    - knn
                    - m2cgen
                    - sqlite
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: tuler/bake-action@73d2e19fd548cbf243722fac4dcc9cfdf701c82b
              with:
                  working-directory: ${{ matrix.dapp}}
                  files: |
                      docker-bake.hcl
                      docker-bake.override.hcl
