# yaml-language-server: =https://json.schemastore.org/github-workflow.json
---
name: "Build echo-python DApp"
on:
    workflow_dispatch:
    pull_request:
        paths:
            - "config/**"
            - "docker/**"
            - "base.hcl"
            - ".github/workflows/dapp-build.yml"
            - ".github/workflows/echo-python-dapp.yml"
            - "echo-python/**"
            - "!**/*.md"
            - "frontend-console/**"
    push:
        tags:
            - v*
        branches:
            - develop
jobs:
    build:
        uses: ./.github/workflows/dapp-build.yml
        with:
            dapp-name: echo-python
        secrets: inherit

    test:
        needs: build
        runs-on: ubuntu-20.04
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Run tests
              env:
                  DAPP_IMAGE: ${{ secrets.DOCKER_ORGANIZATION }}/${{ needs.build.outputs.dapp-image }}
              run: |
                  yarn install
                  yarn test:ci --verbose
              working-directory: ./echo-python/test
